name: EveryJS Publish to NPM
on:
  release:
    types: [created]
jobs:
  deploy-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: cd packages/everyjs && npm i && npm run build
      - name: Install Npm
        run: cd packages/everyjs && npm i -g npm@9 && npm i -g pnpm@7.24.3
      - name: Creating .npmrc
        run: cd packages/everyjs && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
      - name: Publish package on NPM 📦
        run: cd packages/everyjs && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}